package com.board.job.utils;

import com.board.job.util.JwtUtils;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;
import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
public class JwtUtilsTests {
    private final JwtUtils jwtUtils;

    @Autowired
    public JwtUtilsTests(JwtUtils jwtUtils) {
        this.jwtUtils = jwtUtils;
    }

    @Test
    public void testInjectedComponents() {
        assertThat(jwtUtils).isNotNull();
    }

    @Test
    public void testValidGenerateTokenFromEmail() {
        String expected = "username";
        String token = jwtUtils.generateTokenFromEmail(expected);

        String actual = jwtUtils.getSubject(token);

        assertEquals(expected, actual,
                "In this test must be true because we have equals token generated from username " +
                        "and getting subject from right token.");
    }

    @Test
    public void testValidIsValidToken() {
        String token = jwtUtils.generateTokenFromEmail("token");

        assertTrue(jwtUtils.isValidToken(token),
                "In this method should be true because we pass valid jwtToken which is generated by jwtUtils class.");
    }

    @Test
    public void testInvalidIsValidToken() {
        assertFalse(jwtUtils.isValidToken("lkfrgkkSKFLKfefkfl;"),
                "In this method should be false because we pass invalid token.");
    }

    @Test
    public void testValidGetSubject() {
        String expected = "sub";

        String token = jwtUtils.generateTokenFromEmail(expected);
        String actual = jwtUtils.getSubject(token);

        assertEquals(expected, actual,
                "In testing get subject method we should get valid 'username' which is used for creating token.");
    }
}